name: Static Analysis

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy cppcheck

      - name: Generate Compile Commands
        run: make cc

      - name: Run Clang-Tidy
      # clang-tidy automatically looks for compile_commands.json in parent directories
        run: |
          find src include -name "*.cpp" -o -name "*.h" | xargs clang-tidy -p . --warnings-as-errors=* -extra-arg=-std=c++23


       - name: Run Cppcheck
       # Fails the build if any errors are found
        run: |
          cppcheck --enable=all --error-exitcode=1 -i vendor -i build src include

